-- Run this in Supabase SQL Editor.

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  text text not null check (char_length(text) between 1 and 300),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.questions enable row level security;

-- Least-privilege grants.
revoke all on table public.questions from anon, authenticated;
grant insert, select on table public.questions to anon;
grant select, update on table public.questions to authenticated;
grant usage, select on sequence public.questions_id_seq to anon, authenticated;

-- Audience can submit, but only as pending.
create policy "audience can submit pending questions"
on public.questions for insert to anon
with check (status = 'pending');

-- Audience can only read approved questions.
create policy "audience can read approved questions"
on public.questions for select to anon
using (status = 'approved');

-- Signed-in moderators can read all questions.
create policy "moderators can read all questions"
on public.questions for select to authenticated
using (true);

-- Signed-in moderators can moderate.
create policy "moderators can update questions"
on public.questions for update to authenticated
using (true)
with check (status in ('pending','approved','rejected'));

-- Realtime publication. If this errors because the table is already added, that's fine.
alter publication supabase_realtime add table public.questions;
